spring:
  application:
    name: paymentprocessor
  profiles:
    active:
      - qa

  datasource:
    url: jdbc:postgresql://localhost:5432/payment-processor
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
          #naming:
          #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpll
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: 'classpath:db/migration'
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081
  shutdown: graceful
  netty:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 200
      min-spare: 10

external:
  acquiring-bank-gateway:
    endpoint:
      url: http://localhost:8083
  bank-transfer-gateway:
    endpoint:
      url: http://localhost:8082
logging:
  level:
    root: INFO

