openapi: "3.0.3"
info:
  version: "1.0.0"
  title: Bank Transfer Gateway
  description: This service will serve as an entry point into the payment processing system of backend services
  termsOfService: http://www.keelean.com
  contact:
    name: Kingsley Amaeze
    url: http://www.keelean.com
    email: amaezekingsley@ymail.com
  license:
    name: None
    url: http://www.keelean.com
externalDocs:
  description: For information not covered in this specification you can find more details in the link below
  url: http://www.keelean.com

servers:
  - url: http://localhost:8080

paths:
  /api/v1/requestAuthorization:
    post:
      tags:
        - AuthorizeBankTransfer
      summary: For making payments
      description: This endpoint is for making payments
      operationId: authorizeBankTransfer
      requestBody:
        description: This object is used to capture bank payment details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BTBankDetails'
      responses:
        "200":
          description: "Payment completed successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BTPaymentResponse'
        "404":
          description: Error making payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BTPaymentResponse'

components:
  schemas:
    BTPaymentResponse:
      type: object
      description: Captures payment response
      properties:
        message:
          description: The response message
          type: string
          example:
            "Payment successful"
        success:
          description: The
          type: boolean
          example:
            true

    BTBankDetails:
      type: object
      description: Captures bulk upload of users
      properties:
        accountNumber:
          type: string
          description: The payer account number
        bankCode:
          type: string
          description: The payer account number
