spring:
  application:
    name: payment-gateway
  profiles:
    active:
      - qa
  rsocket:
    server:
      port: 7000
  #datasource:
    #url: jdbc:postgresql://localhost:5432/estate-mgt-service
    #username: postgres
    #password: admin
    #driver-class-name: org.postgresql.Driver
  #jpa:
    #open-in-view: false
    #show-sql: true
    #properties:
      #hibernate:
        #format_sql: true
        #generate_statistics: true
        #naming:
          #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpll
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: 'classpath:db/migration'
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  shutdown: graceful
  netty:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 200
      min-spare: 10


external:
  payment-processor:
    endpoint:
      url: http://payment-processor:8080
logging:
  level:
    root: INFO

