openapi: "3.0.3"
info:
  version: "1.0.0"
  title: Acquiring Bank Gateway
  description: This service will send transction data to partner acquiring bank for payment processing
  termsOfService: http://www.keelean.com
  contact:
    name: Kingsley Amaeze
    url: http://www.keelean.com
    email: amaezekingsley@ymail.com
  license:
    name: None
    url: http://www.keelean.com
externalDocs:
  description: For information not covered in this specification you can find more details in the link below
  url: http://www.keelean.com

servers:
  - url: http://localhost:8083

paths:
  /api/v1/payments:
    post:
      tags:
        - ProcessCardPayment
      summary: For making payments
      description: This endpoint is for making payments
      operationId: processCard
      requestBody:
        description: This object is used to capture payment details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PPCardDetails'
      responses:
        "200":
          description: "Payment completed successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PPPaymentResponse'
        "404":
          description: Error making payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PPPaymentResponse'

components:
  schemas:
    PPPaymentResponse:
      type: object
      description: Captures payment response
      properties:
        message:
          description: The response message
          type: string
          example:
            "Payment successful"
        success:
          description: The
          type: boolean
          example:
            true

    PPCardDetails:
      type: object
      description: This object is used to capture error response
      properties:
        cardNumber:
          type: string
          description: The card number
          example:
            5678909087654
        cardName:
          type: string
          description: The card name
          example:
            Kingsley Amaeze
        expiryDate:
          type: string
          description: The card expiry date
          example:
            09/24
        cvv:
          type: integer
          description: The card value verification
          example:
            094
        pin:
          type: integer
          description: The cardholder 4 digit pin
          example:
            094
