openapi: "3.0.3"
info:
  version: "1.0.0"
  title: Payment Processor
  description: Processes payment
  termsOfService: http://www.keelean.com
  contact:
    name: Kingsley Amaeze
    url: http://www.keelean.com
    email: amaezekingsley@ymail.com
  license:
    name: None
    url: http://www.keelean.com
externalDocs:
  description: For information not covered in this specification you can find more details in the link below
  url: http://www.keelean.com

servers:
  - url: http://localhost:8080

paths:
  /api/v1/payments:
    post:
      tags:
        - ProcessPayment
      summary: For making payments
      description: This endpoint is for making payments
      operationId: processPayment
      requestBody:
        description: This object is used to capture payment details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PPPaymentRequest'
      responses:
        "200":
          description: "Payment completed successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PPPaymentResponse'
        "404":
          description: Error making payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PPPaymentResponse'

components:
  schemas:
    PPPaymentRequest:
      type: object
      required:
        - txnAmount
        - txnType
      description: This object is use to capture payment details
      properties:
        txnAmount:
          type: number
          format: double
          description: The amount of the transaction
          example:
            500.98
        txnType:
          type: string
          enum: [ "CARD", "BANK_TRANSFER", "DIGITAL_WALLET" ]
          description: The transaction type
          example:
            "CARD"
        payer:
          $ref: '#/components/schemas/PPPayerDetails'
        payee:
          $ref: '#/components/schemas/PPPayeeDetails'

    PPPaymentResponse:
      type: object
      description: Captures payment response
      properties:
        message:
          description: The response message
          type: string
          example:
            "Payment failed"
        success:
          description: The
          type: boolean
          example:
            false

    PPPayerDetails:
      type: object
      description: This object is used to capture error response
      properties:
        card:
          $ref: '#/components/schemas/PPCardDetails'
        bank:
          $ref: '#/components/schemas/PPBankDetails'

    PPPayeeDetails:
      type: object
      description: This object is used to capture error response
      properties:
        merchant:
          $ref: '#/components/schemas/PPMerchantDetails'

    PPMerchantDetails:
      type: object
      description: This object captures merchant details
      properties:
        merchantCode:
          type: string
          description: The merchant code
        merchantAccount:
          type: string
          description: The merchant account

    PPBankDetails:
      type: object
      description: Captures bulk upload of users
      properties:
        accountNumber:
          type: string
          description: The payer account number
        bankCode:
          type: string
          description: The payer account number

    PPCardDetails:
      type: object
      description: This object is used to capture error response
      properties:
        cardNumber:
          type: string
          description: The card number
          example:
            5678909087654
        cardName:
          type: string
          description: The card name
          example:
            Kingsley Amaeze
        expiryDate:
          type: string
          description: The card expiry date
          example:
            09/24
        cvv:
          type: integer
          description: The card value verification
          example:
            094
        pin:
          type: integer
          description: The cardholder 4 digit pin
          example:
            094
